In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch.optim as optim
from torch.utils.data import TensorDataset,DataLoader

In [5]:
df = pd.read_csv("10 DateFruit_Dataset.csv")

In [6]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [7]:
df.shape

(898, 35)

In [8]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [9]:
df['Class'].unique().shape

(7,)

In [10]:
X = df.drop(['Class'],axis=1)
y = df['Class']

In [11]:
le = LabelEncoder()
y = le.fit_transform(y)

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
X_test

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
331,143957,1452.2620,523.1368,352.3305,0.7392,428.1259,0.9844,146236,0.7746,1.4848,...,-0.3565,4.1478,3.4278,2.4134,-36987568128,-34249711616,-23752157184,77.3446,75.2287,62.9057
638,260563,1975.3740,762.5055,437.8510,0.8187,575.9854,0.9871,263977,0.6648,1.7415,...,0.3581,7.7778,16.2644,3.6606,-2424508160,-4791147520,-8197618688,16.2304,22.3860,28.8860
326,154245,1503.5980,546.4366,361.8018,0.7494,443.1601,0.9883,156070,0.7420,1.5103,...,0.3657,2.4202,2.9624,3.0045,-14960579584,-14010061824,-14057613312,48.2049,46.8561,46.4054
848,317794,2280.9690,875.5868,525.3380,0.8000,636.1037,0.9016,352462,0.6484,1.6667,...,0.3719,2.2682,2.1522,2.9676,-47417053184,-39451316224,-33127270400,58.7696,54.0476,50.8977
39,402279,2295.8630,798.9365,643.2753,0.5931,715.6797,0.9936,404887,0.7867,1.2420,...,1.9477,5.5889,12.5304,9.9496,-30746945536,-32178810880,-35126345728,43.7705,45.6162,46.3010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,283770,2096.7639,775.8751,468.8516,0.7968,601.0883,0.9737,291436,0.6751,1.6548,...,0.8440,11.0456,12.1213,6.1299,-4560918528,-7281993216,-9060293632,20.5245,25.8721,29.4805
25,381508,2239.7891,734.2203,666.2502,0.4202,696.9584,0.9919,384642,0.7398,1.1020,...,2.0740,6.6729,10.5392,9.3474,-25635362816,-25228310528,-28113027072,41.0071,41.1774,41.5364
84,253276,1961.0400,740.2677,437.3487,0.8068,567.8741,0.9822,257864,0.7493,1.6926,...,-0.1425,2.0920,1.9879,2.1549,-45574098944,-41109114880,-35898662912,64.4454,61.4443,58.3921
10,364495,2216.4900,790.9014,590.7698,0.6649,681.2411,0.9949,366374,0.7658,1.3388,...,0.9283,3.0514,4.3653,6.0898,-41679380480,-40727969792,-37574615040,52.7269,52.9888,50.3108
332,156030,1566.9790,595.6793,384.2388,0.7641,445.7169,0.9118,171132,0.6319,1.5503,...,-0.3529,2.5952,2.3904,2.6668,-33837977600,-33563627520,-25646532608,70.7212,71.3609,63.4659

In [14]:
Scaler = StandardScaler()

X_train_scaled = Scaler.fit_transform(X_train)
X_test_scaled = Scaler.transform(X_test)

# Converting Data Into Tensors

In [15]:
X_train_tensor = torch.tensor(X_train_scaled,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,dtype=torch.long)

# DataSet

In [16]:
train_dataset = TensorDataset(X_train_tensor,y_train_tensor)
test_dataset = TensorDataset(X_test_tensor,y_test_tensor)

# DataLoader

In [17]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32)

# ANN

In [18]:
class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()

    self.model = nn.Sequential(
        #1st hidden layer
        nn.Linear(X.shape[1],64),
        nn.ReLU(),
        #2nd hidden layer
        nn.Linear(64,64),
        nn.ReLU(),

        nn.Linear(64,7)

    )
  def forward(self,X):

    return self.model(X)

# Loss Calculation

In [19]:
model = ANN()

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

# Training Loop

In [20]:
epochs = 100

for epoch in range(epochs):

  model.train()
  running_loss = 0.0

  for batch_features,batch_labels in train_loader:
    outputs = model(batch_features)
    loss = criterion(outputs,batch_labels)

    # backward
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    running_loss = running_loss + loss.item()

  train_loss = running_loss / len(train_loader)

  print(f"Epoch : {epoch}/{epochs}, Loss : {train_loss}")

Epoch : 0/100, Loss : 1.6808567980061406
Epoch : 1/100, Loss : 1.106262585391169
Epoch : 2/100, Loss : 0.7347057351599569
Epoch : 3/100, Loss : 0.5573010146617889
Epoch : 4/100, Loss : 0.4627457636853923
Epoch : 5/100, Loss : 0.39126461485157843
Epoch : 6/100, Loss : 0.34689230374667956
Epoch : 7/100, Loss : 0.31576359466366144
Epoch : 8/100, Loss : 0.2894393354654312
Epoch : 9/100, Loss : 0.26867850643137225
Epoch : 10/100, Loss : 0.2527325982632844
Epoch : 11/100, Loss : 0.2373313281847083
Epoch : 12/100, Loss : 0.21931433580491855
Epoch : 13/100, Loss : 0.2172967104808144
Epoch : 14/100, Loss : 0.20688135565622992
Epoch : 15/100, Loss : 0.19190796432287796
Epoch : 16/100, Loss : 0.1829408251720926
Epoch : 17/100, Loss : 0.18568573600572089
Epoch : 18/100, Loss : 0.1882450062295665
Epoch : 19/100, Loss : 0.16997156988667406
Epoch : 20/100, Loss : 0.1598754393989625
Epoch : 21/100, Loss : 0.15207619867894961
Epoch : 22/100, Loss : 0.1513669038920299
Epoch : 23/100, Loss : 0.1488696453363999
Epoch : 24/100, Loss : 0.1380062135665313
Epoch : 25/100, Loss : 0.14002765034851822
Epoch : 26/100, Loss : 0.13352762680986655
Epoch : 27/100, Loss : 0.12588130536934602
Epoch : 28/100, Loss : 0.12290005005248215
Epoch : 29/100, Loss : 0.11748866137603055
Epoch : 30/100, Loss : 0.12470297029484874
Epoch : 31/100, Loss : 0.12064871645492056
Epoch : 32/100, Loss : 0.11339311771418738
Epoch : 33/100, Loss : 0.11516281193041283
Epoch : 34/100, Loss : 0.10953954169931619
Epoch : 35/100, Loss : 0.1084243517531001
Epoch : 36/100, Loss : 0.10397167293273885
Epoch : 37/100, Loss : 0.10089635079645592
Epoch : 38/100, Loss : 0.10091167939421923
Epoch : 39/100, Loss : 0.10847384774166605
Epoch : 40/100, Loss : 0.10590377470235461
Epoch : 41/100, Loss : 0.10364311415216197
Epoch : 42/100, Loss : 0.0974172550537016
Epoch : 43/100, Loss : 0.08887585681741653
Epoch : 44/100, Loss : 0.08773564846943253
Epoch : 45/100, Loss : 0.0828857894015053
Epoch : 46/100, Loss : 0.08269943592503019
Epoch : 47/100, Loss : 0.08103572842462556
Epoch : 48/100, Loss : 0.07843669155693572
Epoch : 49/100, Loss : 0.07847676199415456
Epoch : 50/100, Loss : 0.07485295953633993
Epoch : 51/100, Loss : 0.07617954982687598
Epoch : 52/100, Loss : 0.07896648679414521
Epoch : 53/100, Loss : 0.07614742401663376
Epoch : 54/100, Loss : 0.0730822202547089
Epoch : 55/100, Loss : 0.07435049744241912
Epoch : 56/100, Loss : 0.07124112635526968
Epoch : 57/100, Loss : 0.06730179310492847
Epoch : 58/100, Loss : 0.06546605698278417
Epoch : 59/100, Loss : 0.07018748557438022
Epoch : 60/100, Loss : 0.06361382584209027
Epoch : 61/100, Loss : 0.0610724129187672
Epoch : 62/100, Loss : 0.07035697300149046
Epoch : 63/100, Loss : 0.06571477181885553
Epoch : 64/100, Loss : 0.06452813706077311
Epoch : 65/100, Loss : 0.06073163943770139
Epoch : 66/100, Loss : 0.06124227959662676
Epoch : 67/100, Loss : 0.05732470329688943
Epoch : 68/100, Loss : 0.06148933594965417
Epoch : 69/100, Loss : 0.056520303265879986
Epoch : 70/100, Loss : 0.05350249645340702
Epoch : 71/100, Loss : 0.05960297511647577
Epoch : 72/100, Loss : 0.05226249438103126
Epoch : 73/100, Loss : 0.049268818703358586
Epoch : 74/100, Loss : 0.04939811166537845
Epoch : 75/100, Loss : 0.05440185980304428
Epoch : 76/100, Loss : 0.050324079054205315
Epoch : 77/100, Loss : 0.04839500958990792
Epoch : 78/100, Loss : 0.05023453273284047
Epoch : 79/100, Loss : 0.05086354980164248
Epoch : 80/100, Loss : 0.04750367782443114
Epoch : 81/100, Loss : 0.047586385666838156
Epoch : 82/100, Loss : 0.04517769515919297
Epoch : 83/100, Loss : 0.043684302242067846
Epoch : 84/100, Loss : 0.04325290514237207
Epoch : 85/100, Loss : 0.04345726703151898
Epoch : 86/100, Loss : 0.04505411223710879
Epoch : 87/100, Loss : 0.044709864396439945
Epoch : 88/100, Loss : 0.04013328130721398
Epoch : 89/100, Loss : 0.0451204068351375
Epoch : 90/100, Loss : 0.04360467845412052
Epoch : 91/100, Loss : 0.04185845468031323
Epoch : 92/100, Loss : 0.0380084247470064
Epoch : 93/100, Loss : 0.03412831574678421
Epoch : 94/100, Loss : 0.03383596364975623
Epoch : 95/100, Loss : 0.03661872741118397
Epoch : 96/100, Loss : 0.036237326339292136
Epoch : 97/100, Loss : 0.03200787526514867
Epoch : 98/100, Loss : 0.030824316685776346
Epoch : 99/100, Loss : 0.03162092134437483

# Evaluation

In [21]:
total = 0
correct = 0

model.eval()

with torch.no_grad():

  for batch_features,batch_labels in test_loader:
    outputs = model(batch_features)

    _,predicted = torch.max(outputs,1)          # maximum value return korbe

    correct +=(predicted == batch_labels).sum().item()
    total += batch_labels.size(0)

print(f"Total Values : {total}")
print(f"Correct Values : {correct}")

print(f"Accuracy : {correct/total * 100}")

Total Values : 180
Correct Values : 167
Accuracy : 92.77777777777779